# Custom Language File for Launcher Customizer

[ejs.app]
title = "Synesia Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Mat40/SynesiaLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/vxEBxAB6Xq"

[ejs.settings]
sourceGithubLink = "https://github.com/Mat40/SynesiaLauncher"
supportLink = "https://github.com/Mat40/SynesiaLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR SYNESIA"
welcomeDescription = "Bienvenue, aventurier intrépide, sur notre serveur Minecraft moddé, où la technologie rencontre la magie et dévoile un univers fascinant qui n'attend que vous pour l'explorer !"
welcomeDescCTA = ""
